# .gitlab-ci.yml
#

stages:
  - test
  - build


image:                             tetcoin/rust:nightly

variables:
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_HOME:                      "${CI_PROJECT_DIR}/.cargo"

cache:
  key:                             "${CI_JOB_NAME}"
  paths:
    - ./.cargo/


#### stage:                        test

test:rust:stable:
  stage:                           test
  script:
    - time cargo test --verbose --all --features bit-vec,generic-array,vec-array,derive
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

test:rust:stable:no_derive:
  stage:                           test
  script:
    - time cargo test --verbose --features bit-vec,generic-array,vec-array
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

check:rust:stable:no_derive_no_std_full:
  stage:                           test
  script:
    - time cargo check --verbose --no-default-features --features bit-vec,generic-array,vec-array,full
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

check:rust:stable:no_derive_no_std:
  stage:                           test
  script:
    - time cargo check --verbose --no-default-features --features bit-vec,generic-array,vec-array
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

check:rust:stable:no_derive_full:
  stage:                           test
  script:
    - time cargo check --verbose --features bit-vec,generic-array,vec-array,full
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

bench:rust:nightly:
  stage:                           test
  script:
    - time cargo +nightly bench --features bit-vec,generic-array,vec-array,derive
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

#### stage:                        build

build:linux:ubuntu:amd64:
  stage:                           build
  script:
    - cargo build --verbose --release --features bit-vec,generic-array,vec-array,derive
  only:
    - master
    - tags
    - web
  tags:
    - rust
