[package]
name = "tetsy-scale-codec"
version = "1.3.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetsy SCALE - Simple Concatenating Aggregated Little Endians"
license = "Apache-2.0"
edition = "2018"
keywords = [ "tetcoin", "tetcore", "vapory" ]
categories = [ "cryptography::cryptocurrencies", "encoding" ]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetsy-scale-codec"
documentation = "https://docs.rs/tetsy-scale-codec"

[dependencies]
arrayvec = { version = "0.5.1", default-features = false, features = ["array-sizes-33-128", "array-sizes-129-255"] }
serde = { version = "1.0.102", optional = true }
tetsy-scale-codec-derive = { path = "derive", version = "1.2.0", default-features = false, optional = true }
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"], optional = true }
byte-slice-cast = { version = "0.3.4", default-features = false, features = ["alloc"] }
generic-array = { version = "0.13.2", optional = true }

[dev-dependencies]
criterion = "0.3.0"
serde_derive = { version = "1.0" }
tetsy-scale-codec-derive = { path = "derive", version = "^1.0.2", default-features = false }
quickcheck = "0.9"

[[bench]]
name = "benches"
harness = false

[lib]
bench = false

[features]
default = ["std"]
derive = ["tetsy-scale-codec-derive"]
std = ["serde", "bitvec/std", "byte-slice-cast/std"]
bit-vec = ["bitvec"]

# WARNING: DO _NOT_ USE THIS FEATURE IF YOU ARE WORKING ON CONSENSUS CODE!*
#
# Provides implementations for more data structures than just Vec and Box.
# Concretely it will provide tetsy-scale-codec implementations for many types
# that can be found in std and/or alloc.
full = []

[workspace]
members = [
	"derive",
	"fuzzer",
]
