[package]
name = "codec-fuzzer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Vincent Ulitzsch <vincent@srlabs.de>"]
edition = "2018"
publish = false

[dependencies]
tetsy-scale-codec = { path = "../", features = [ "derive", "bit-vec" ] }
honggfuzz = "0.5.45"
bitvec = { version = "0.17.4", features = ["alloc"] }
